services:
  - type: web
    name: digitaldingo
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: digitaldingo-data
      mountPath: /data
      sizeGB: 1