services:
  - type: web
    name: digitaldingo
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.11.1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 